-- --- SCRIPT COMPLETO DE CRIAÇÃO DO BANCO (VIVO ESSENTIAL) ---

-- 1. Sequência para a Tabela de Usuários
CREATE SEQUENCE VE_USUARIOS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

-- 2. Tabela de Usuários (VE_USUARIOS)
-- (Script corrigido para espelhar 100% o user.entity.ts)
CREATE TABLE VE_USUARIOS (
    ID_USUARIO      NUMBER DEFAULT VE_USUARIOS_SEQ.NEXTVAL NOT NULL,
    EMAIL           VARCHAR2(255) NOT NULL,
    SENHA_HASH      VARCHAR2(255) NOT NULL,
    NOME_COMPLETO   VARCHAR2(300) NOT NULL,
    TIPO_PERFIL     VARCHAR2(50)  NOT NULL,
    DATA_CADASTRO   DATE DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO    NUMBER(1) DEFAULT 1 NOT NULL,
    
    -- Colunas que faltavam (baseado no user.entity.ts):
    TELEFONE        VARCHAR2(20) NULL,
    DESCRICAO       VARCHAR2(500) NULL,
    DIAS_OFENSIVA   NUMBER DEFAULT 0 NOT NULL,
    VIVO_COINS      NUMBER DEFAULT 0 NOT NULL,
    ID_GESTOR       NUMBER NULL,
    ID_BUDDY        NUMBER NULL,
    
    -- Constraints
    CONSTRAINT PK_VE_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_VE_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_VE_USUARIOS_TIPO_PERFIL CHECK (TIPO_PERFIL IN ('NOVO_COLABORADOR', 'BUDDY', 'GESTOR')),
    CONSTRAINT CK_VE_USUARIOS_STATUS_ATIVO CHECK (STATUS_ATIVO IN (0, 1))
);

-- 3. Sequência para a Tabela de Avaliações
CREATE SEQUENCE VE_AVALIACOES_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

-- 4. Tabela de Avaliações (VE_AVALIACOES)
-- (Necessária para a home_newuser.html)
CREATE TABLE VE_AVALIACOES (
    ID_AVALIACAO    NUMBER DEFAULT VE_AVALIACOES_SEQ.NEXTVAL NOT NULL,
    ID_USUARIO      NUMBER NOT NULL,
    HUMOR           NUMBER NOT NULL,
    COMENTARIO      VARCHAR2(1000),
    DATA_AVALIACAO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_VE_AVALIACOES PRIMARY KEY (ID_AVALIACAO),
    CONSTRAINT FK_VE_AVALIACOES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES VE_USUARIOS(ID_USUARIO)
);

-- Comentários (Opcional, mas boa prática)
COMMENT ON COLUMN VE_USUARIOS.VIVO_COINS IS 'Moedas de gamificação';
COMMENT ON COLUMN VE_AVALIACOES.ID_USUARIO IS 'ID do usuário que fez a avaliação';
COMMENT ON COLUMN VE_AVALIACOES.HUMOR IS 'A nota do humor (1 a 5)';