-- Arquivo: 01_create_tables.sql

-- Primeiro, criamos a sequência para o ID_USUARIO
CREATE SEQUENCE VE_USUARIOS_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE
  NOCYCLE
  CACHE 20;

-- Agora, criamos a tabela VE_USUARIOS
CREATE TABLE VE_USUARIOS (
    ID_USUARIO      NUMBER DEFAULT VE_USUARIOS_SEQ.NEXTVAL NOT NULL,
    EMAIL           VARCHAR2(255) NOT NULL,
    SENHA_HASH      VARCHAR2(255) NOT NULL,
    NOME_COMPLETO   VARCHAR2(300) NOT NULL,
    TIPO_PERFIL     VARCHAR2(50)  NOT NULL,
    DATA_CADASTRO   DATE DEFAULT SYSDATE NOT NULL,
    STATUS_ATIVO    NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_VE_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_VE_USUARIOS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_VE_USUARIOS_TIPO_PERFIL CHECK (TIPO_PERFIL IN ('NOVO_COLABORADOR', 'BUDDY', 'GESTOR')),
    CONSTRAINT CK_VE_USUARIOS_STATUS_ATIVO CHECK (STATUS_ATIVO IN (0, 1))
);

-- Comentários nas colunas (opcional, mas boa prática)
COMMENT ON COLUMN VE_USUARIOS.ID_USUARIO IS 'Identificador único do usuário (Chave Primária)';
COMMENT ON COLUMN VE_USUARIOS.EMAIL IS 'Email do usuário, usado para login (Único)';
COMMENT ON COLUMN VE_USUARIOS.SENHA_HASH IS 'Hash da senha do usuário';
COMMENT ON COLUMN VE_USUARIOS.NOME_COMPLETO IS 'Nome completo do usuário';
COMMENT ON COLUMN VE_USUARIOS.TIPO_PERFIL IS 'Tipo de perfil do usuário (NOVO_COLABORADOR, BUDDY, GESTOR)';
COMMENT ON COLUMN VE_USUARIOS.DATA_CADASTRO IS 'Data de cadastro do usuário na plataforma';
COMMENT ON COLUMN VE_USUARIOS.STATUS_ATIVO IS 'Status da conta do usuário (1=Ativo, 0=Inativo)';